---
- name: Deploy Maven Artifact
  hosts: local
  become: false
  tasks:
    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/pg8/target/myapp-1.0-SNAPSHOT.jar"
        dest: "sudo /home/ubuntu/lab/"

